# Generated by Django 2.2.16 on 2023-02-19 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20230218_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='follow',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Статус отписки'),
        ),
    ]
